### PR TITLE
fix: good bio :)

### LINKED ISSUE #557: [Bug]: When I make changes to my bio in settings, what appears is a mix of a placeholder text, such as 'Lorem,' and my actual bio.
### What happened?

image
Proposed solution : 
If the bio is empty, display the placeholder; if it's not empty, show only the bio.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by KaKashi1210**
small win ig

fixes #557

### CODE REVIEW

**Review by KaKashi1210 — COMMENTED** [review]
LGTM?

File: apps/web/src/components/user/dashboard/index.tsx [hunk 1]
```diff
@@ -82,9 +82,10 @@ export default async function Dashboard({ user }: Props) {
               Joined {getRelativeTime(user.createdAt)}
             </p>
             <div className="mb-4 mt-2 w-full text-center text-sm md:w-64 md:text-start">
-              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minima temporibus maiores
-              nesciunt hic dolores aspernatur corrupti laboriosam consectetur. Vitae, consectetur?
-              <ReactMarkdown>{user.bio}</ReactMarkdown>
+              { !user.bio?
```
Comment (maxdemaio) [inline apps/web/src/components/user/dashboard/index.tsx]: Could we just have it as `{user.bio}` and it will just remain empty if it's `null`? I checked GitHub and it looks like that's what they do 👍🏻

So no ternary but I'd just double check how it looks when `null` is passed as a child to the `ReactMarkdown` component :shipit:

**Review by Hacksore — APPROVED** [review]

**Review by maxdemaio — APPROVED** [review]

**Comment by maxdemaio** [comment]
Ran this on my local and it looks good! Thank you @KaKashi1210 🔥
