### PR TITLE
bug: admins can delete any solution

### LINKED ISSUE #1025: [Bug]: Admins should be able to delete solutions (or anything really)
### What happened?

Admins should be able to delete solutions

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by zaCKoZAck0**
Admins can now delete solutions
## Related Issue

Closes #1025

### CODE REVIEW

**Review by bautistaaa — APPROVED** [review]

File: apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/solution-detail.tsx [hunk 1]
```diff
@@ -137,7 +137,7 @@ export function SolutionDetails({ solution }: Props) {
               ) : null}
 
               {/* Only author can see edit / delete button */}
-              {isAuthor(session, solution.userId) ? (
+              {isAuthor(session, solution.userId) || isAdminOrModerator(session) ? (
```
Comment (bautistaaa) [inline apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/solution-detail.tsx:140]: should update comment above or remove
