### PR TITLE
fix: editor shortcuts and vimconfig styling

### LINKED ISSUE #519: [Feature]: Settings Modal Needs Some Love
### Description

If someone who is good at design wants to fix the [`/apps/web/src/app/challenge/_components/settings/settings-form.tsx`](https://github.com/bautistaaa/typehero/tree/main/apps/web/src/app/challenge/_components/settings/settings-form.tsx) file, I recently added a vim config textarea but I had no clue how to style it in a way that doesn't suck

(this is what it currently looks like):
image

### PR DESCRIPTION
**Pull request by kualta**
1. Added pills to shortcuts
2. Changed shortcuts icon
3. Fix size & only show vim config when using vim bindings

closes #519

### CODE REVIEW

**Comment by Hacksore** [comment]
@kualta need a fix of the eslint failing checks

File: apps/web/src/app/challenge/_components/editor-shortcuts/editor-shortcuts-button.tsx [hunk 1]
```diff
@@ -8,16 +8,16 @@ import {
   TooltipContent,
   TooltipTrigger,
 } from '@repo/ui';
-import { Command } from '@repo/ui/icons';
 import { EditorShortcuts } from './editor-shortcuts-form';
+import { SquareSlash } from 'lucide-react';
```
Comment (Tylopilus) [inline apps/web/src/app/challenge/_components/editor-shortcuts/editor-shortcuts-button.tsx:12]: better add the icon to the icons pkg instead of importing from lib directly?

**Comment by kualta** [comment]
@Hacksore done

**Review by bautistaaa — APPROVED** [review]
