### PR TITLE
Fix : Editor shortcuts update #761

### LINKED ISSUE #761: [Bug]: Editor shortcuts
### What happened?

Some of the editor shortcuts are invalid. Additionally, they dont account for the users Operating System and always displays `ctrl` 

This ticket involves a couple requirements

- [ ] detect operating systems and display `ctrl` or `cmd` accordingly. 
- [ ] remove shortcuts that dont apply (ex: `Run Code` can be deleted)
- [ ] adjust shortcuts that arent accurate (ex: indent one level is `TAB or ⌘ + ]`
- [ ] any other improvements i may have missed

### Current List
CleanShot 2023-10-02 at 22 24 02@2x

can use leetcode for reference
https://leetcode.com/problems/two-sum/

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by vivekKumarSinghH**
## Description

Remove irrelevant shortcuts (Run and Submit code)
Update inaccurate shortcuts
Dynamic shortcut rendering for mac OS (Alt and Ctrl key)
## Related Issue

Closes #761 

## How Has This Been Tested?
Tested locally

## Screenshots/Video (if applicable):
image

image

### CODE REVIEW

**Comment by bautistaaa** [comment]
i dont think we need debug either since this is all at the type level

File: apps/web/src/app/[locale]/challenge/_components/editor-shortcuts/editor-shortcuts-form.tsx [hunk 1]
```diff
@@ -23,87 +23,67 @@ const Key = (props: PropsWithChildren) => {
     </kbd>
   );
 };
-
+function isMacOS() {
+  return navigator.platform.toLowerCase().includes('mac');
+}
 export function EditorShortcuts() {
+  const cmdOrCtrl = isMacOS() ? 'Cmd' : 'Ctrl';
+  const optionOrAlt = isMacOS() ? 'Option' : 'Alt';
```
Comment (QuiiBz) [inline apps/web/src/app/[locale]/challenge/_components/editor-shortcuts/editor-shortcuts-form.tsx:31]: Probably not worth it because the variable name isn't great (and the perf difference is probably VERY small), but we can avoid calling `isMacOS` two times:
```suggestion
  const isMac = isMacOS()
  const cmdOrCtrl = isMac ? 'Cmd' : 'Ctrl';
  const optionOrAlt = isMac ? 'Option' : 'Alt';
```

**Comment by bautistaaa** [comment]
can you run `pnpm checks:fix`

**Comment by vivekKumarSinghH** [comment]
> can you run `pnpm checks:fix`

should i commit all the file change to my branch?

**Review by Hacksore — APPROVED** [review]
