### PR TITLE
Fix: scroll to top of really long solution

### LINKED ISSUE #1011: [Bug]: Unable to scroll to top with a really long solution.
### What happened?

If you were to write a long enough solution for any solution. You're unable to scroll to the top to get to the `Preview` button (both via mouse or via keyboard arrow keys). The video below demonstrates the problem.

[Screencast from 2023-10-31 11-41-35.webm](https://github.com/typehero/typehero/assets/36449128/80350c53-dc48-4318-bf35-de71308a17e7)

### What browsers are you seeing the problem on?

All

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by oreoluwa-bs**
## Description
Allow scrolling while creating a really long solution.
- Overflow set to auto and a relative position on the parent container

## Related Issue

Closes #1011 

## Motivation and Context

#1011 

## How Has This Been Tested?

No tests

## Screenshots/Video (if applicable):
https://github.com/typehero/typehero/assets/46888096/50aa0cad-ee25-4ee7-9998-0a60d8873e3d

### CODE REVIEW

File: apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/solution-editor.tsx [hunk 1]
```diff
@@ -117,7 +117,7 @@ export function SolutionEditor({ dismiss, challenge }: Props) {
             Post
           </Button>
         </div>
-        <div className="flex flex-1 flex-col">
+        <div className="relative flex flex-1 flex-col overflow-auto">
```
Comment (bautistaaa) [inline apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/solution-editor.tsx:120]: why do we need relative

Comment (oreoluwa-bs) [reply apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/solution-editor.tsx]: I tried to make the toolbar stick to the top earlier guess I forgot to take that out.

**Review by bautistaaa — APPROVED** [review]
