### PR TITLE
fix: add delay for AvatarFallback

### LINKED ISSUE #1607: [Bug]: The fallback for user avatar flashes before the real avatar loads
### What happened?

fallback avatar should only display after we have confirmed the user is not logged in

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

```zsh
To reproduce you can login and just refresh the home page and look at your avatar top right.

This can also be observed anywhere you see a user avatar since its reused
```

### PR DESCRIPTION
**Pull request by rozhkoy**
## Related Issue
closes #1607

### CODE REVIEW

File: apps/web/src/components/Navigation/index.tsx [hunk 1]
```diff
@@ -167,7 +167,7 @@ async function LoginButton({
         >
           <Avatar className="h-7 w-7">
             <AvatarImage src={session.user.image ?? ''} alt="user avatar" />
-            <AvatarFallback>
+            <AvatarFallback delayMs={5000}>
```
Comment (bautistaaa) [inline apps/web/src/components/Navigation/index.tsx:170]: theres another place to do it in the `apps/aot` directory. can you take a look

**Comment by bautistaaa** [comment]
i went ahead and consolidated avatar into one component to use across platforms

**Review by bautistaaa — APPROVED** [review]

**Comment by rozhkoy** [comment]
> i went ahead and consolidated avatar into one component to use across platforms

nice
